### ISSUE TITLE
Small window dropdown

### ISSUE THREAD

**Issue by dcmid** [theRedditLoop/Website#21]
When the window is made small, the options do disappear but are not replaced by a dropdown. A small rectangle appears which links to "#". This was encountered in Google Chrome.
![redditloopsmall](https://cloud.githubusercontent.com/assets/7914186/8263016/c77acce8-169c-11e5-94d2-9ce699cf45b7.png)

**Comment by jdublu10** [comment]
This should have been fixed in #19 
Do you have the most updated version of master-qa?

**Comment by dcmid** [comment]
git says I'm up to date...

**Comment by jdublu10** [comment]
Note: This issue does not seem to exist in dev.redditloop.co, which is a deployed version of master-qa

**Comment by dcmid** [comment]
I think it was my cache. I opened dev tools and reloaded the file and it is fixed. My bad.

**Comment by jdublu10** [comment]
It's likely. If you reference #19 you can see that only the class of the tag was changed, which probably isn't enough for chrome to re-cache the page.
