### ISSUE TITLE
Make Media Page

### ISSUE THREAD

**Issue by jdublu10** [theRedditLoop/Website#28]
Media page will contain:
* Latest youtube video
* Latest 3 tweets
* Concept art gallery

**Comment by jdublu10** [comment]
@zlsa would you be kind enough to throw together a design for this page while I get the API jazz sorted out?

**Comment by jdublu10** [comment]
Media page is currently in progress. You can view it by checking out feature/mediaPage#28. There are no images and no video currently on the site, but both will be added when we have them. Also waiting on the twitter API token.

**Comment by ablankenship10** [comment]
What is the status of this? Is this closed after PR #30?

**Comment by jdublu10** [comment]
Should be good.
