### ISSUE TITLE
Gradient covers background image on smaller screens

### ISSUE THREAD

**Issue by ablankenship10** [theRedditLoop/Website#8]
![image](https://cloud.githubusercontent.com/assets/1980841/8239908/f454ebf2-15cc-11e5-9ccc-e1f3eb25385b.png)

Suggest making the background image with a transparent background + put gradient on the body element.

**Comment by zlsa** [comment]
It should fade out to rgba(0, 0, 0, 0), not the background color.

**Comment by jdublu10** [comment]
on it

**Comment by ablankenship10** [comment]
Also, the position of the text has changed

**Comment by ablankenship10** [comment]
Resolved
